ALL_QUESTIONS = [
    # ── 簡単 (≤5語) ──────────────────────────────────────────
    "See you later.",
    "That's a great idea.",
    "How are you doing?",
    "I'll be right back.",
    "Nice to meet you.",
    "It's getting late.",
    "I'm so tired today.",
    "You're taller than he is.",
    "What time is it?",
    "I don't know.",
    "That sounds good.",
    "Let me think.",
    "Be careful, please.",
    "I'm on my way.",
    "See you tomorrow.",
    "That's very kind.",
    "Take your time.",
    "Good luck today.",
    "I'm almost ready.",
    "Not bad at all.",
    "That makes sense.",
    "I'll try again.",
    "You did great.",
    "No problem at all.",
    "What's going on?",
    "I'm feeling great.",
    "That's really nice.",
    "I need help.",
    "Have a great day.",
    "What do you think?",
    "Let's get started.",
    "Don't worry about it.",
    "I'm very sorry.",
    "You're so funny.",
    "That's not right.",
    "How about now?",
    "I can do it.",
    "Let's go home.",
    "I miss you.",
    "Call me later.",
    "Here you go.",
    "How was school?",
    "I'll be there.",
    "Are you ready?",
    "I feel sick.",
    "Let me know.",
    "What's your name?",
    "I like it.",
    "Yes, of course.",
    "I'm not sure.",
    "Thank you so much.",
    "I'm home now.",
    "Please sit down.",
    "Excuse me, please.",
    "I'm running late.",
    "I agree with you.",
    "How do you feel?",
    "That's wonderful news.",
    "I'll take it.",
    "Let's eat out.",
    "I love this.",
    "You're absolutely right.",
    "It's my fault.",
    "I changed my mind.",
    "Can you hear me?",
    "I'm doing fine.",
    "That was delicious.",
    "I'll figure it out.",
    "I forgot about it.",
    "Let's try again.",
    "It's not that bad.",
    "I'm proud of you.",
    "I'll get it.",
    "Are you serious?",
    "That's a deal.",
    "I'm just kidding.",
    "You look tired.",
    "I'll check it.",
    "It happened again.",
    "I'm almost done.",
    "You were right.",
    "Good job today.",
    "No, thank you.",
    "I'm on it.",
    "Tell me more.",
    "That's too bad.",
    "I'll explain later.",
    "I made a mistake.",
    "What's the matter?",
    "Keep it up.",
    "It's up to you.",
    "Hang in there.",
    "I'll be fine.",
    "That's all right.",
    "I'm with you.",
    "Good morning, everyone.",
    "Well done, everyone.",
    "Good night, everyone.",
    "Ready or not.",
    "I'll pass today.",
    "Please call me later.",
    "Please wait over there.",
    "Please take a seat.",
    "Please close the door.",
    "Please open the window.",
    "Please answer the phone.",
    "Please bring your bag.",
    "Please check your email.",
    "Please follow me.",
    "Please drive carefully.",
    "Please speak slowly.",
    "Please listen carefully.",
    "Please come inside.",
    "Please go ahead.",
    "Please stay here.",
    "Please wait downstairs.",
    "Please leave it there.",
    "Please try it again.",
    "Please write it down.",
    "Please send it today.",
    "Please keep the change.",
    "Please hold the line.",
    "Please save this file.",
    "Please wash your hands.",
    "Please turn left here.",
    "Please turn right there.",
    "Please hurry up.",
    "Please don't be late.",
    "Please don't forget.",
    "I can't hear you.",
    "I can't see it.",
    "I can't find it.",
    "I can't believe it.",
    "I can't remember that.",
    "I can't open this.",
    "I can't decide yet.",
    "I can't stay long.",
    "I can't come today.",
    "I can't sleep well.",
    "I can't stop laughing.",
    "I can't wait anymore.",
    "I should leave now.",
    "I should call her.",
    "I should study tonight.",
    "I should eat something.",
    "I should ask first.",
    "I should check again.",
    "I should go soon.",
    "I should rest today.",
    "I need more time.",
    "I need some water.",
    "I need your help.",
    "I need a break.",
    "I need this receipt.",
    "I need to sleep.",
    "I need to practice.",
    "I need to leave.",
    "I need to hurry.",
    "I lost my ticket.",
    "I lost my phone.",
    "I found my keys.",
    "I found your notebook.",
    "I brought your coffee.",
    "I bought a sandwich.",
    "I made some tea.",
    "I sent the email.",
    "I read your message.",
    "I heard the news.",
    "I checked the schedule.",
    "I missed the train.",
    "I missed your call.",
    "I changed the plan.",
    "I cleaned my room.",
    "I finished my homework.",
    "I passed the test.",
    "I failed the exam.",
    "I forgot my password.",
    "I remember that place.",
    "I understand your point.",
    "I appreciate your help.",
    "I trust your judgment.",
    "I enjoyed the movie.",
    "I like this song.",
    "I like your jacket.",
    "I love that idea.",
    "I hate waiting outside.",
    "I prefer hot coffee.",
    "I prefer window seats.",
    "We can start now.",
    "We can leave soon.",
    "We can try again.",
    "We can meet tomorrow.",
    "We can walk there.",
    "We can share this.",
    "We can discuss it.",
    "We can fix that.",
    "We can finish today.",
    "We can take turns.",
    "We should go now.",
    "We should hurry up.",
    "We should ask someone.",
    "We should be careful.",
    "We should leave early.",
    "We should call first.",
    "We should check again.",
    "We should stay together.",
    "We should meet downstairs.",
    "They arrived early today.",
    "They left without me.",
    "They forgot the tickets.",
    "They changed the schedule.",
    "They canceled the meeting.",
    "They called this morning.",
    "They finished before noon.",
    "They waited outside.",
    "They seemed very happy.",
    "They looked really tired.",
    "She looks very busy.",
    "She sounds upset today.",
    "She seems quite nervous.",
    "She arrived on time.",
    "She left too early.",
    "She called me yesterday.",
    "She wrote it down.",
    "She brought some snacks.",
    "She forgot her bag.",
    "She needs more practice.",
    "He looks very tired.",
    "He sounds really excited.",
    "He arrived quite late.",
    "He left his phone.",
    "He called after lunch.",
    "He sent the files.",
    "He forgot my name.",
    "He needs your advice.",
    "He bought new shoes.",
    "He made a mistake.",
    "The train is late.",
    "The bus is crowded.",
    "The room is quiet.",
    "The window is open.",
    "The door is locked.",
    "The coffee is cold.",
    "The tea is hot.",
    "The shop is closed.",
    "The movie was boring.",
    "The movie was great.",
    "The weather looks nice.",
    "The weather changed quickly.",
    "The meeting starts soon.",
    "The meeting ended early.",
    "The restaurant is full.",
    "The hotel looks expensive.",
    "The ticket was cheap.",
    "The answer seems correct.",
    "The plan sounds simple.",
    "The road is busy.",
    "My phone is dead.",
    "My bag is heavy.",
    "My hands are cold.",
    "My throat feels dry.",
    "My train was delayed.",
    "My meeting starts soon.",
    "My schedule is full.",
    "My English is improving.",
    "My computer stopped working.",
    "My brother called yesterday.",
    "Your idea sounds useful.",
    "Your answer is correct.",
    "Your phone is ringing.",
    "Your bag looks heavy.",
    "Your room looks clean.",
    "Your message was clear.",
    "Your timing was perfect.",
    "Your voice sounds different.",
    "Your train leaves soon.",
    "This chair is broken.",
    "This coffee tastes great.",
    "This soup is too salty.",
    "This room feels cold.",
    "This lesson is useful.",
    "This sentence is easy.",
    "This problem looks difficult.",
    "This place feels familiar.",
    "This plan might work.",
    "This ticket is valid.",
    "That was really helpful.",
    "That was my mistake.",
    "That was quite surprising.",
    "That seems fair enough.",
    "That looks too expensive.",
    "That sounds a little strange.",
    "That happened last week.",
    "That took too long.",
    "That went pretty well.",
    "That feels much better.",
    "Is this seat taken?",
    "Is everything okay now?",
    "Is the door locked?",
    "Is your phone working?",
    # ── 普通 (6〜9語) ─────────────────────────────────────────
    "Could you please say that again?",
    "I'm not sure what time it starts.",
    "She said she would call back later.",
    "We've been waiting here for almost an hour.",
    "Do you know where the subway station is?",
    "I'd like to make a reservation, please.",
    "Can you help me find what I need?",
    "I didn't realize how difficult this would be.",
    "Would you mind if I opened the window?",
    "He's been working on that project for months.",
    "He wanted to know if breakfast was included.",
    "I think we should leave before it gets late.",
    "Could you tell me the way to the station?",
    "I'm looking forward to seeing you this weekend.",
    "What would you like to have for dinner?",
    "I've never been to that part of town.",
    "Do you have any plans for the weekend?",
    "I'd rather stay home than go out tonight.",
    "He said he would be there by six.",
    "Can you pass me the salt, please?",
    "I need to finish this before the deadline.",
    "She forgot to bring her umbrella this morning.",
    "Would you like some more coffee or tea?",
    "Have you ever tried Japanese food before?",
    "The weather has been terrible all week long.",
    "I'll give you a call when I arrive.",
    "Could you show me how to use this?",
    "They've been friends since they were in school.",
    "Please let me know if you need anything.",
    "He always stays late to finish his work.",
    "I need to make a phone call quickly.",
    "She told me the store was having a sale.",
    "Would you like to come with us tonight?",
    "I lost my wallet somewhere on the way here.",
    "Can you give me a hand with this?",
    "I'm looking for someone who speaks English well.",
    "Do you think the rain will stop soon?",
    "I was surprised to see you at the party.",
    "Would you mind waiting here for just a moment?",
    "I forgot to turn off the air conditioner.",
    "She asked if I was available on Saturday.",
    "I'm glad we finally had a chance to meet.",
    "He didn't know what to say at first.",
    "Could you speak a bit more slowly, please?",
    "I'm not feeling well, so I'm going home.",
    "Would you be able to come a bit earlier?",
    "She left the office before anyone else did.",
    "Do you happen to know what time it closes?",
    "I'd like to order the same thing as you.",
    "Can you recommend a good place to eat nearby?",
    "I'm sorry I missed your call this morning.",
    "He asked me to pick him up at five.",
    "Would you prefer coffee or tea this morning?",
    "She turned off the lights before leaving the room.",
    "Do you know when the next bus is coming?",
    "I was just about to call you right now.",
    "He said the restaurant was fully booked tonight.",
    "Could you tell me how to get there?",
    "I'm running a bit late, so please wait.",
    "She handed in her report before the deadline.",
    "I didn't sleep well at all last night.",
    "He sent me an email about the meeting.",
    "Can you show me the way to the hotel?",
    "I'm thinking about taking up a new hobby.",
    "She was surprised to hear the good news.",
    "Do you have a few minutes to talk?",
    "He seems to be getting better every day.",
    "I'm looking for a good English conversation class.",
    "Could you lend me your umbrella for today?",
    "She told me the store opens at nine.",
    "Would you like to come with me instead?",
    "I've been really busy with work this week.",
    "He promised to return the book by Friday.",
    "Can you help me with this math problem?",
    "I'm thinking of changing my hairstyle soon.",
    "She reminded me to buy milk on the way.",
    "Do you know what time the movie starts?",
    "I was hoping you could join us today.",
    "He needs to leave by seven at the latest.",
    "Could you please wait outside for a moment?",
    "I haven't talked to him in quite a while.",
    "She was excited to hear about the promotion.",
    "Would it be okay if I used your charger?",
    "I had such a great time at the concert.",
    "He told me to go straight and turn left.",
    "Can you help me figure out this problem?",
    "I'm not sure if I locked the door.",
    "She gave me some good advice about the job.",
    "I don't think I've ever been here before.",
    "He looks like he could use some rest.",
    "Could you bring me another glass of water?",
    "I just realized I left my keys at home.",
    "She's been learning to drive for about six months.",
    "Would you like some help with your luggage?",
    "I think I need to take a short break.",
    "He barely had time to eat his lunch today.",
    "Can I ask you a personal question?",
    "I'll try to finish it by this evening.",
    "She's always known exactly what she wanted to do.",
    "Do you need me to translate that for you?",
    "Could you call me after the meeting?",
    "Could you bring the documents to my desk?",
    "Could you check the schedule one more time?",
    "Could you explain that in simpler words?",
    "Could you help me carry this box?",
    "Could you lend me your pen for a moment?",
    "Could you send me the file by email?",
    "Could you tell me where to wait?",
    "Could you show me how this works?",
    "Could you repeat the last sentence, please?",
    "Could you speak a little louder, please?",
    "Could you wait here until I come back?",
    "Could you write your name on this form?",
    "Could you open the door for me?",
    "Could you close the window before you leave?",
    "Could you turn off the lights upstairs?",
    "Could you pick up some milk tonight?",
    "Could you remind me about the appointment?",
    "Could you take a picture for us?",
    "Could you help me choose a gift?",
    "Can you meet me outside the station?",
    "Can you check if the door is locked?",
    "Can you tell me when dinner is ready?",
    "Can you help me find my phone?",
    "Can you pass me that blue folder?",
    "Can you explain why the train was delayed?",
    "Can you remember what she said yesterday?",
    "Can you let me know before you leave?",
    "Can you make sure everyone is ready?",
    "Can you give me ten more minutes?",
    "Can you tell whether this milk is fresh?",
    "Can you see the sign across the street?",
    "Can you hear the music from next door?",
    "Can you help me move this table?",
    "Can you read the message out loud?",
    "Can you tell me your honest opinion?",
    "Can you wait until the rain stops?",
    "Can you call the restaurant for a table?",
    "Can you bring an extra chair over here?",
    "Can you check the price before buying it?",
    "Would you like to join us for lunch?",
    "Would you mind closing the door behind you?",
    "Would you mind speaking more slowly this time?",
    "Would you prefer to sit by the window?",
    "Would you like me to call you tomorrow?",
    "Would you be free after work today?",
    "Would you like to try some of this?",
    "Would you rather walk or take the bus?",
    "Would you mind waiting outside for five minutes?",
    "Would you like another cup of coffee?",
    "Would you be able to help us today?",
    "Would you mind checking this page for errors?",
    "Would you like to come over this weekend?",
    "Would you prefer tea instead of coffee?",
    "Would you mind if we left a bit early?",
    "Would you be interested in seeing the museum?",
    "Would you like to hear the good news?",
    "Would you please keep your voice down?",
    "Would you mind taking your shoes off here?",
    "Would you like directions to the hotel?",
    "I have to leave for work soon.",
    "I forgot to bring my charger today.",
    "I need to buy some groceries after work.",
    "I want to improve my English this year.",
    "I didn't know the store closed early.",
    "I think this train goes to the airport.",
    "I hope the weather is nice tomorrow.",
    "I heard you moved to a new apartment.",
    "I thought the meeting was at three.",
    "I found a good cafe near the office.",
    "I left my umbrella on the train.",
    "I lost my keys somewhere this morning.",
    "I need a little more time to decide.",
    "I wanted to ask you something important.",
    "I should have checked the address earlier.",
    "I haven't seen that movie yet.",
    "I don't remember where I put it.",
    "I didn't expect the test to be difficult.",
    "I was happy to hear your news.",
    "I was hoping you would come today.",
    "I was about to send you a message.",
    "I think we took the wrong train.",
    "I believe we can finish this by Friday.",
    "I hope you feel better by tomorrow.",
    "I heard the new restaurant is very popular.",
    "I thought you were coming with us.",
    "I forgot to set my alarm last night.",
    "I need to return this book today.",
    "I want to take a short break.",
    "I couldn't hear what the teacher said.",
    "She asked me to call her later.",
    "She told me the meeting had been canceled.",
    "She said she would arrive around seven.",
    "She left her bag in the classroom.",
    "She wants to study abroad next year.",
    "She forgot to send the report yesterday.",
    "She seemed nervous before the presentation started.",
    "She decided to stay home this evening.",
    "She was waiting for us outside.",
    "She promised to help me after lunch.",
    "She asked whether I had eaten breakfast.",
    "She explained the rule very clearly.",
    "She bought a small gift for her friend.",
    "She called me as soon as she arrived.",
    "She finished her homework before dinner.",
    "She remembered to bring the tickets this time.",
    "She was looking for a place to sit.",
    "She needs to practice speaking every day.",
    "She wanted to know where we were going.",
    "She sent me the address this morning.",
    "He asked me to wait for him.",
    "He said he was running a little late.",
    "He forgot to bring his notebook to class.",
    "He told me not to worry about it.",
    "He wants to change his seat on the plane.",
    "He left the office earlier than usual.",
    "He needs to finish the report by tomorrow.",
    "He promised to call when he got home.",
    "He was surprised by the final score.",
    "He decided to take the later train.",
    "He asked if the shop was still open.",
    "He explained how to use the new app.",
    "He bought tickets for the concert tonight.",
    "He called the hotel to confirm the booking.",
    "He finished eating before everyone else did.",
    "He remembered my name after all these years.",
    "He was looking for his wallet everywhere.",
    "He needs to get more sleep at night.",
    "He wanted to know why I was absent.",
    "He sent the wrong file by mistake.",
    "We need to leave before it gets dark.",
    "We should check the map before we go.",
    "We can talk about the details tomorrow.",
    "We had dinner at a small restaurant.",
    "We missed the bus by a few minutes.",
    "We found a quiet place to study.",
    "We need to decide by tomorrow morning.",
    "We should meet at the station entrance.",
    "We can take a taxi if necessary.",
    "We were surprised by how crowded it was.",
    "We had to wait outside for an hour.",
    "We decided to cancel the plan tonight.",
    "We should ask someone at the information desk.",
    "We can review the notes after class.",
    "We need to bring enough water for everyone.",
    "We should arrive at least ten minutes early.",
    "We can use this room until noon.",
    "We had trouble finding the right building.",
    "We decided to walk instead of driving.",
    "We should make a reservation before going there.",
    "They asked us to wait in line.",
    "They said the train would be delayed.",
    "They forgot to lock the front door.",
    "They decided to move to another city.",
    "They arrived just before the movie started.",
    "They wanted to try a different restaurant.",
    "They were talking about the weekend trip.",
    "They found a cheaper hotel near the station.",
    "They promised to send the photos later.",
    "They finished the work earlier than expected.",
    "They asked whether we needed any help.",
    "They explained the rules before the game started.",
    "They bought snacks for everyone in the office.",
    "They called to say they were delayed.",
    "They remembered to bring enough food today.",
    "They were looking for a quiet place.",
    "They need to prepare for tomorrow's meeting.",
    "They wanted to know what happened yesterday.",
    "They sent us the invitation by email.",
    "They decided not to go out tonight.",
    "The train was delayed because of the rain.",
    "The bus stops right in front of the hotel.",
    "The meeting started later than we expected.",
    "The store closes earlier on Sundays.",
    "The restaurant was full when we arrived.",
    "The weather changed suddenly in the afternoon.",
    "The movie was much better than I expected.",
    "The room was too warm for sleeping.",
    "The coffee here is stronger than usual.",
    "The hotel is only five minutes away.",
    "The class begins at nine every morning.",
    "The elevator is out of service today.",
    "The price includes breakfast and free coffee.",
    "The road was closed after the accident.",
    "The ticket machine was not working properly.",
    "The new schedule starts from next Monday.",
    "The final answer was easier than expected.",
    "The teacher gave us homework for tomorrow.",
    "The office was quieter than usual today.",
    "The problem was fixed before lunch.",
    "This is the book I told you about.",
    "This looks like the place we visited before.",
    "This sounds like a good chance for us.",
    "This might be harder than we first thought.",
    "This should be finished by tomorrow afternoon.",
    "This tastes better than the one yesterday.",
    "This room is available until three o'clock.",
    "This message came from the hotel staff.",
    "This lesson helped me understand the topic better.",
    "This road leads directly to the station.",
    # ── 難しい (10語〜) ────────────────────────────────────────
    "They're trying to fix the problem, but so far they've had no luck.",
    "I'll have to check my schedule and get back to you on that.",
    "It's been a long time since we last saw each other, hasn't it?",
    "Could you please repeat that a little more slowly so I can understand?",
    "I was wondering if you could give me some advice about this situation.",
    "By the time we arrived at the station, the train had already left.",
    "I didn't realize how much work was involved until we actually got started.",
    "She mentioned that she was thinking about looking for a new position abroad.",
    "If you ever need anything, please don't hesitate to let me know.",
    "The meeting was supposed to start at nine, but it got pushed back.",
    "I've been meaning to call you, but things have been really busy lately.",
    "He told me that the project was finally approved after months of delays.",
    "Would it be possible for us to reschedule the appointment to next week?",
    "I'm not sure whether we should take the highway or the back roads.",
    "She said she would send the documents over as soon as she could.",
    "We should probably leave a little earlier to avoid getting stuck in traffic.",
    "I'm afraid I won't be able to attend the conference due to a conflict.",
    "Could you let me know what time works best for you to meet?",
    "He's been studying really hard for his exams and could use some support.",
    "I just heard that the company is planning to expand into new markets.",
    "She apologized for the delay and promised it wouldn't happen again in the future.",
    "I didn't expect so many people to show up for the event last night.",
    "Could you please tell me where I can find the nearest convenience store?",
    "He explained that the reason for the cancellation was due to bad weather.",
    "I've been looking forward to this trip for the past several months now.",
    "Would you be interested in joining us for dinner after the presentation tonight?",
    "We've been trying to solve this issue for quite some time without any success.",
    "He mentioned that he was planning to take a few days off next week.",
    "I just wanted to let you know that the package has finally been delivered.",
    "She did an incredible job presenting the proposal to the board of directors.",
    "If everything goes according to plan, we should be finished by Friday afternoon.",
    "I'm a bit concerned about the weather forecast for the upcoming weekend trip.",
    "He said he would try his best to finish the report before the meeting.",
    "Could you do me a favor and double-check these figures before the presentation?",
    "I've never seen so many people at the station at this time of day.",
    "She's been working really hard to meet the deadline, and it's starting to show.",
    "Would you mind if I asked you a few questions about your experience here?",
    "I was hoping we could find some time to go over the details together.",
    "He didn't realize how important it was to submit the form before the deadline.",
    "I think the best approach would be to tackle the most urgent issues first.",
    "She told her team that they needed to be more careful with the data.",
    "We're planning to have a small get-together at our place this coming Saturday.",
    "He's been commuting for over two hours every day for the past several years.",
    "Would it be alright if we moved the meeting to a different time slot?",
    "I wasn't expecting the feedback to be so positive, but I'm really glad it was.",
    "She made sure that all the necessary arrangements were made well in advance.",
    "I'm trying to decide whether to take the train or drive to the airport.",
    "He's looking forward to presenting his ideas to the team at the next meeting.",
    "Could you please confirm whether the event is still scheduled for next Thursday?",
    "I had a really good time at the conference, and I learned a lot.",
    "She's been feeling a bit under the weather, so she decided to stay home.",
    "We should probably set aside some time to go over the budget together soon.",
    "He asked me to review the contract before sending it to the other party.",
    "I was relieved to hear that everyone made it home safely after the storm.",
    "Would you be willing to stay a bit late tonight to help finish the project?",
    "She's been doing a lot of research on the topic and is quite knowledgeable.",
    "I think we should reconsider our approach before we proceed any further with this.",
    "He reminded everyone that the deadline was approaching and that we needed to hurry.",
    "She said the new system would take some getting used to, but it's worth it.",
    "I'm not sure I fully understand the situation, so could you please explain it again?",
    "Could you please make sure that all the doors are locked before you leave tonight?",
    "I was surprised to find out that the store had already closed for the day.",
    "She decided to take a completely different route home because of the construction nearby.",
    "We're going to need everyone's cooperation if we want this project to succeed.",
    "I just wanted to check in and see how things are going on your end.",
    "He apologized for not responding sooner and promised to follow up right away.",
    "Would you mind reviewing this document and letting me know your thoughts on it?",
    "I'm planning to take some time off after finishing this big project next month.",
    "He said the interview went really well and that he felt good about his chances.",
    "She took great care to explain every detail so that no one would be confused.",
    "We ended up spending the entire afternoon trying to figure out what had gone wrong.",
    "He made it very clear that he wasn't happy with the way things were handled.",
    "Could you send me the agenda for the meeting so I can prepare in advance?",
    "I'm looking forward to the opportunity to work with such a talented group of people.",
    "She mentioned that she would be out of the office for the rest of the week.",
    "We appreciate your patience and apologize for any inconvenience this may have caused.",
    "I realize this is short notice, but I was wondering if you were available tomorrow.",
    "He worked through the night to make sure everything was ready for the morning meeting.",
    "I've been trying to get in touch with you, but I keep missing your calls.",
    "She managed to finish the presentation on time despite all the last-minute changes.",
    "Would it be possible to get an extension on the deadline for this particular assignment?",
    "I've been so busy lately that I haven't had much time for anything else at all.",
    "He was really impressed by the amount of effort everyone put into the project.",
    "She pointed out that there was an error in the report that needed to be corrected.",
    "We should schedule a follow-up meeting to discuss the results of the initial review.",
    "I appreciate everything you've done for me, and I'll never forget your kindness.",
    "He reminded us that we should always double-check our work before submitting it.",
    "I'm having second thoughts about the decision we made at yesterday's meeting.",
    "I hadn't realized until now just how much progress we've actually made together.",
    "She asked if we could reschedule the call because something urgent had come up.",
    "He said the new policy would take effect starting from the beginning of next month.",
    "I think we all need to take a step back and look at the bigger picture here.",
    "Could you please forward that email to me so I can take a look at it?",
    "She was glad to hear that the client was satisfied with the final result.",
    "We'll need to finalize the budget proposal before the end of the fiscal quarter.",
    "I don't think we've considered all the possible risks associated with this approach.",
    "He asked everyone to keep the details of the project strictly confidential for now.",
    "I'm not entirely comfortable with the direction things are heading at the moment.",
    "She was relieved to find out that the problem had already been taken care of.",
    "We should make sure that all team members are on the same page going forward.",
    "I just found out that the deadline has been moved up to next Monday morning.",
    "I was hoping we could talk about the plan before the meeting starts.",
    "Could you please check the address again before we leave for the station?",
    "She told me she would call as soon as she got home.",
    "He wanted to know whether the price included breakfast and free coffee.",
    "We should leave a little earlier so we do not miss the train.",
    "I did not realize the store closed so early on Sunday evenings.",
    "Could you let me know when you have finished reading the document?",
    "She asked if I could help her carry the boxes upstairs.",
    "He said the hotel was much closer to the station than expected.",
    "I was surprised to see so many people waiting outside the restaurant.",
    "We decided to take the bus because the rain was getting heavier.",
    "Could you please speak more slowly so everyone can understand the instructions?",
    "She forgot to bring her umbrella even though the forecast said rain.",
    "He promised to send me the photos after he got back home.",
    "I think we should review the notes once more before the test.",
    "They asked us to arrive at least ten minutes before the meeting.",
    "I need to return this book to the library before it closes.",
    "She said the movie was better than she had expected it to be.",
    "He was looking for a quiet place where he could study alone.",
    "Could you help me find the email that you sent yesterday morning?",
    "We were planning to visit the museum, but it was closed today.",
    "I left my phone on the table when I went outside.",
    "She wanted to know if we had already bought the train tickets.",
    "He asked me to remind him about the appointment tomorrow morning.",
    "I think this restaurant is the one my friend recommended last week.",
    "Could you tell me what time the next train leaves from here?",
    "We should make a reservation before going there on a Friday night.",
    "She seemed relieved when she heard that everyone had arrived safely.",
    "He told me not to worry because the problem was already fixed.",
    "I was about to leave the office when you called me.",
    "They decided to walk to the hotel because it was nearby.",
    "Could you please make sure the windows are closed before you leave?",
    "I forgot to check the weather before I left home this morning.",
    "She said she had never seen the station so crowded before.",
    "He needs to finish the report before the client meeting tomorrow afternoon.",
    "We found a small cafe where we could wait until noon.",
    "I did not expect the lesson to be so useful for speaking practice.",
    "Could you ask the teacher whether we need to submit it today?",
    "She was excited to hear that her application had finally been accepted.",
    "He said the new schedule would start from the beginning of next week.",
    "I think we took the wrong exit at the last station.",
    "We should ask someone at the counter before making a decision.",
    "They told us the room would be available after three o'clock.",
    "Could you bring an extra chair because one more person is coming?",
    "I was glad to hear that your presentation went well yesterday.",
    "She left the meeting early because she had another appointment downtown.",
    "He remembered to lock the door before leaving the house this time.",
    "We decided to stay inside until the heavy rain had stopped.",
    "I need to buy a new charger because mine stopped working.",
    "Could you check whether there are any seats left for tonight?",
    "She explained the rules clearly so nobody would make the same mistake.",
    "He wanted to try the local food, but the menu looked confusing.",
    "I was nervous at first, but the interview went better than expected.",
    "We had to wait for almost an hour outside the station.",
    "Could you send me the link again so I can open it?",
    "She told me that the package would arrive by tomorrow afternoon.",
    "He looked tired because he had been working since early morning.",
    "I think we should talk to everyone before changing the plan.",
    "They found a cheaper hotel that was still close to the station.",
    "Could you please remind me to call the office after lunch?",
    "I did not know the museum was free on the first Sunday.",
    "She asked me to check the spelling before sending the message.",
    "He said he would bring the documents to the office tomorrow.",
    "We should leave enough time to find the right platform.",
    "I was hoping you could help me practice this sentence once more.",
    "Could you tell me whether this bus goes directly to the airport?",
    "She was disappointed because the concert tickets had already sold out.",
    "He asked everyone to keep their phones silent during the meeting.",
    "I forgot where I parked the car after leaving the shopping mall.",
    "We decided to order the same dish because it looked delicious.",
    "Could you please wait here while I ask for directions?",
    "She said the coffee was too strong for her to drink.",
    "He told me the road was closed because of construction nearby.",
    "I think this is the best option we have right now.",
    "They were surprised by how quickly the weather changed this afternoon.",
    "Could you check the timetable before we decide when to leave?",
    "I left the receipt in my bag, so I can show it later.",
    "She needs to practice every day if she wants to improve quickly.",
    "He said the meeting would be shorter than usual this week.",
    "We were looking for a place where we could sit quietly.",
    "Could you ask if they have a table for four tonight?",
    "I was about to cook dinner when my friend called me.",
    "She told me not to forget to bring my passport.",
    "He was happy to hear that the client liked the final result.",
    "I think we should finish the hardest task before taking a break.",
    "They decided to cancel the picnic because the weather looked bad.",
    "Could you please turn down the music while I am studying?",
    "I did not realize how far the hotel was from here.",
    "She said she would join us if she finished work early.",
    "He asked me where I had bought the jacket I was wearing.",
    "We need to decide who will present each part of the report.",
    "I was relieved to find out that my wallet was still there.",
    "Could you send the agenda before the meeting so we can prepare?",
    "She forgot to save the file before her computer shut down.",
    "He said the restaurant was famous for its breakfast and coffee.",
    "We should review the budget before we agree to the proposal.",
    "I thought the class would be difficult, but it was quite enjoyable.",
    "Could you tell me how long it takes to walk there?",
    "She asked whether I had enough time to finish the work.",
    "He wanted to leave early so he could catch the last train.",
    "We found out that the shop had moved to another street.",
    "I need to practice speaking clearly before taking the actual test.",
    "Could you please explain the difference between these two options again?",
    "She said the view from the top floor was really beautiful.",
    "He promised to help us clean the room after the event.",
    "We decided to meet in front of the station at six thirty.",
    "I was surprised that the answer was simpler than I expected.",
    "Could you tell me where I should put these extra chairs?",
    "She wanted to know if the restaurant accepted credit cards.",
    "He forgot to tell me that the plan had changed yesterday.",
    "We should write down the address in case our phones stop working.",
    "I did not expect the train to be so crowded this morning.",
    "Could you please keep this seat for me while I buy coffee?",
    "She told me that learning a language takes time and patience.",
    "He said the office would be closed during the national holiday.",
    "We need to check the details before sending the final message.",
    "I was happy to hear that you enjoyed the trip so much.",
    "Could you ask the driver to stop near the next traffic light?",
    "She looked worried because she could not find her boarding pass.",
    "He told everyone to arrive early and bring something to write with.",
    "We should choose a restaurant that is not too far from here.",
    "I was trying to remember the name of the book you mentioned.",
    "Could you let me know if the meeting time changes again?",
    "She said she would explain everything after the guests had left.",
    "He wanted to check the room before signing the rental agreement.",
    "We decided to postpone the trip because several people were busy.",
    "I forgot to bring a jacket, so I felt cold outside.",
    "Could you please help me carry these bags to the car?",
    "She asked me to wait until she finished talking to the manager.",
    "He said he could not come because he had to work late.",
    "We need to buy enough food for everyone before the party starts.",
    "I was surprised to learn that the store opened at seven.",
    "Could you check if there is a faster way to get there?",
    "She told me the class would be held in a different room.",
    "He forgot to charge his phone before leaving the house.",
    "We decided to take a short break after finishing the first section.",
    "I think the safest choice is to ask for more information.",
    "Could you please tell me whether I should sign this form?",
    "She said she had already sent the email to the whole team.",
    "He was disappointed when he heard that the game had been canceled.",
    "We should make sure everyone understands the plan before we begin.",
    "I did not know that your office was so close to mine.",
    "Could you show me where the nearest ticket machine is located?",
    "She wanted to take a picture before the sun went down.",
    "He said he was sorry for arriving late to the appointment.",
    "We found a quiet table near the window and sat down.",
    "I need to call my family before I board the plane.",
    "Could you tell me if this seat is still available?",
    "She asked me to bring the printed documents to the meeting.",
    "He wanted to know how much time we had left.",
    "We should clean the room before the guests arrive this evening.",
    "I thought I had enough time, but I was wrong.",
    "Could you please check the door before going to bed tonight?",
    "She said the lesson was useful because it included real conversations.",
    "He asked me not to share the news until tomorrow.",
    "We decided to walk home because the evening weather was pleasant.",
    "I forgot to bring cash, so I had to use my card.",
    "Could you tell me what you thought about the presentation today?",
    "She told me that the answer was written on the next page.",
    "He said the problem started after the system was updated.",
    "We should find a place to eat before the shops close.",
    "I was glad that the train arrived only a few minutes late.",
    "Could you please pass this message to the person at reception?",
    "She asked if I would be available for a short call.",
    "He wanted to practice the sentence until it sounded natural.",
    "We need to finish this part before moving on to the next.",
    "I thought the museum would be crowded, but it was quiet.",
    "Could you let me know once you have checked the details?",
    "She said the new cafe near the station was worth visiting.",
    "He forgot to bring his lunch, so he bought a sandwich.",
    "We should arrive early because the entrance might be crowded today.",
    "I was worried that I had sent the email to the wrong person.",
    "Could you please write down the address so I do not forget it?",
    "She told me that the meeting room was on the third floor.",
    "He said he would wait outside until we were ready.",
    "We decided to stop for coffee before going back to the office.",
    "I did not understand the question until she explained it again.",
    "Could you ask whether the tickets are still available for tonight?",
    "She wanted to know why the schedule had changed so suddenly.",
    "He said the report was almost finished but needed one more review.",
    "We should take a picture of the sign before we leave.",
    "I was surprised by how easy the instructions were to follow.",
    "Could you please make a copy of this document for me?",
    "She told everyone to write their names at the top of the page.",
    "He asked me to call him if anything changed during the day.",
    "We need to leave soon if we want to arrive on time.",
    "I thought the food would be spicy, but it was quite mild.",
    "Could you tell me where I can find a taxi stand nearby?",
    "She said she was looking forward to seeing everyone again soon.",
    "He forgot the name of the restaurant where we had lunch.",
    "We decided to wait inside because the wind was getting stronger.",
    "I was happy that the teacher remembered my question from last week.",
    "Could you please check whether this sentence sounds natural in English?",
    "She asked me to explain the problem in my own words.",
    "He said the presentation would take about fifteen minutes to finish.",
    "We should keep practicing until the sentence becomes easier to repeat.",
    "I did not realize the station had so many different exits.",
    "Could you tell me which platform the airport train leaves from?",
    "She told me that her flight had been delayed by bad weather.",
]
